apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    

spec:
  selector:
    matchLabels:
      app: myapps
    
  replicas: 3

  template:
    metadata:
      name: nginx
      labels:    
        app: myapps
        
    spec:
       containers:
       - name: nginx
         image: nginx


      



  
  
